-- Adicionar campo que indica se o registo está atualizado ou não
ALTER TABLE AGE_RATINGS ADD COLUMN IS_UP_TO_DATE TINYINT NOT NULL DEFAULT 0;
ALTER TABLE DIRECTORS ADD COLUMN IS_UP_TO_DATE TINYINT NOT NULL DEFAULT 0;
ALTER TABLE TYPES ADD COLUMN IS_UP_TO_DATE TINYINT NOT NULL DEFAULT 0;
ALTER TABLE GENRES ADD COLUMN IS_UP_TO_DATE TINYINT NOT NULL DEFAULT 0;
ALTER TABLE CONTENTS ADD COLUMN IS_UP_TO_DATE TINYINT NOT NULL DEFAULT 0;
ALTER TABLE CONTENT_GENRES ADD COLUMN IS_UP_TO_DATE TINYINT NOT NULL DEFAULT 0;

-- Atualizar valor dos registos existentes para 0 (não atualizados)
SET SQL_SAFE_UPDATES = 0;
UPDATE AGE_RATINGS SET IS_UP_TO_DATE = 0 WHERE AGE_RATING_ID IS NOT NULL;
UPDATE DIRECTORS SET IS_UP_TO_DATE = 0 WHERE DIRECTOR_ID IS NOT NULL;
UPDATE TYPES SET IS_UP_TO_DATE = 0 WHERE TYPE_ID IS NOT NULL;
UPDATE GENRES SET IS_UP_TO_DATE = 0 WHERE GENRE_ID IS NOT NULL;
UPDATE CONTENTS SET IS_UP_TO_DATE = 0 WHERE CONTENT_CODE IS NOT NULL;
UPDATE CONTENT_GENRES SET IS_UP_TO_DATE = 0 WHERE CONTENT_CODE IS NOT NULL;
SET SQL_SAFE_UPDATES = 1;

-- Criar triggers para atualizar o campo IS_UP_TO_DATE para 0 quando um registo é atualizado
CREATE TRIGGER trg_update_age_ratings
BEFORE UPDATE ON AGE_RATINGS
FOR EACH ROW
SET NEW.IS_UP_TO_DATE = IF(@DISABLE_IS_UP_TO_DATE_TRIGGER IS NULL OR @DISABLE_IS_UP_TO_DATE_TRIGGER = 0, 0, NEW.IS_UP_TO_DATE);

CREATE TRIGGER trg_update_directors
BEFORE UPDATE ON DIRECTORS
FOR EACH ROW
SET NEW.IS_UP_TO_DATE = IF(@DISABLE_IS_UP_TO_DATE_TRIGGER IS NULL OR @DISABLE_IS_UP_TO_DATE_TRIGGER = 0, 0, NEW.IS_UP_TO_DATE);

CREATE TRIGGER trg_update_types
BEFORE UPDATE ON TYPES
FOR EACH ROW
SET NEW.IS_UP_TO_DATE = IF(@DISABLE_IS_UP_TO_DATE_TRIGGER IS NULL OR @DISABLE_IS_UP_TO_DATE_TRIGGER = 0, 0, NEW.IS_UP_TO_DATE);

CREATE TRIGGER trg_update_genres
BEFORE UPDATE ON GENRES
FOR EACH ROW
SET NEW.IS_UP_TO_DATE = IF(@DISABLE_IS_UP_TO_DATE_TRIGGER IS NULL OR @DISABLE_IS_UP_TO_DATE_TRIGGER = 0, 0, NEW.IS_UP_TO_DATE);

CREATE TRIGGER trg_update_contents
BEFORE UPDATE ON CONTENTS
FOR EACH ROW
SET NEW.IS_UP_TO_DATE = IF(@DISABLE_IS_UP_TO_DATE_TRIGGER IS NULL OR @DISABLE_IS_UP_TO_DATE_TRIGGER = 0, 0, NEW.IS_UP_TO_DATE);

CREATE TRIGGER trg_update_content_genres
BEFORE UPDATE ON CONTENT_GENRES
FOR EACH ROW
SET NEW.IS_UP_TO_DATE = IF(@DISABLE_IS_UP_TO_DATE_TRIGGER IS NULL OR @DISABLE_IS_UP_TO_DATE_TRIGGER = 0, 0, NEW.IS_UP_TO_DATE);