version: '3.8'

services:
  postgres1:
    image: postgres:latest
    container_name: postgres1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5434:5432"

  postgres2:
    image: postgres:latest
    container_name: postgres2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5435:5432"

  mysql:
    image: mysql:latest
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: password3
      MYSQL_DATABASE: db3
      MYSQL_USER: user3
      MYSQL_PASSWORD: password3
    command: --local-infile=1
    ports:
      - "3307:3306"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dw
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./data_generation/csv_dimensional_model:/csv_dimensional_model
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  sql_data: